const fs = require('fs')

const data = {
    maxWeight:94,
    numberOfItems:15,
    items:[
        {
            id:1,
            utility:5,
            weight:21,
        },
        {
            id:2,
            utility:24,
            weight:1
        },
        {
            id:3,
            utility:3,
            weight:9,
        },
        {
            id:4,
            utility:4,
            weight:26
        },
        {
            id:5,
            utility:3,
            weight:10
        },
        {
            id:6,
            utility:13,
            weight:28,
        },
        {
            id:7,
            utility:11,
            weight:28
        },
        {
            id:8,
            utility:1,
            weight:10
        },
        {
            id:9,
            utility:11,
            weight:16
        },
        {
            id:10,
            utility:23,
            weight:2
        },
        {
            id:11,
            utility:24,
            weight:26
        },
        {
            id:12,
            utility:2,
            weight:15
        },
        {
            id:13,
            utility:21,
            weight:21
        },
        {
            id:14,
            utility:11,
            weight:20
        },
        {
            id:15,
            utility:14,
            weight:2
        }

    ]
};
fs.writeFile('./items.json',JSON.stringify(data),()=>{
    console.log('successfully')
})